#!/usr/bin/env bash
# Install nginx
sudo apt-get update
sudo apt-get -y install nginx
echo 'user www-data;
worker_processes 4;
pid /run/nginx.pid;

events {
        worker_connections 768;
}

http {
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        gzip on;
        gzip_disable "msie6";

    server {
        listen 80;
        server_name localhost;
        location / {
            root /home;
        }
        error_page 404 /404.html;
        location = /404.html {
            root /home;
        }
        location /redirect_me {
            rewrite ^/redirect_me http://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
        }
    }
}' | sudo tee /etc/nginx/nginx.conf > /dev/null
sudo service nginx start
sudo service nginx reload
echo "Holberton School" | sudo tee /home/index.html
echo "Ceci n'est pas une page" | sudo tee /home/404.html
