#!/usr/bin/env bash
# Install nginx
sudo apt-get -y install nginx
sudo nginx
echo 'user www-data;
worker_processes 4;
pid /run/nginx.pid;

events {
        worker_connections 768;
}

http {
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        gzip on;
        gzip_disable "msie6";

        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;
}


http {
    server {
        location / {
            root /home/ubuntu;
        }
        error_page 404 /404.html;
        location = /404.html {
                root /home/ubuntu;
        }
http {
    server {
        location / {
            root /home/ubuntu;
        }
        error_page 404 /404.html;
        location = /404.html {
            root /home/ubuntu;
        }
        location /redirect_me {
            rewrite ^/redirect_me http://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
        }
    }
}' | sudo tee /etc/nginx/nginx.conf > /dev/null
sudo nginx -s reload
echo "Holberton School" > index.html
echo "Ceci n'est pas une page" > 404.html
