#!/usr/bin/env bash
# display 1 to 20 with bad luck numbers from China, Japan, and Italy
i="1"

while [ $i -lt 21 ]
do
echo $i
if [ $i -eq 4 ]; then
echo "bad luck from China"
elif [ $i -eq 9 ]; then
echo "bad luck from Japan"
elif [ $i -eq 17 ]; then
echo "bad luck from Italy"
elif [ $i -eq 25 ]; then
echo 'this gets around "case"'
fi
i=$((i+1))
done
