#!/usr/bin/env bash
# Print Holberton School and bad luck or good luck
i="1"

while [ $i -lt 11 ]
do
if [ $i -eq 4 ]; then
echo "bad luck"
elif [ $i -eq 8 ]; then
echo "good luck"
else
echo "Holberton School"
fi
i=$((i+1))
done
